//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadium2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StadiumId { get; set; }
        public System.DateTime StartTime { get; set; }
        public int Time { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual MyStadium MyStadium { get; set; }
        public virtual User User { get; set; }
    }
}
